#!/usr/bin/env ruby

# from http://techspeak.plainlystated.com/2009/03/watching-your-logs-from-console.html
# def show_log
#   unless @log_buffer_size
#     @log_file = Rails.logger.instance_variable_get("@log")
#     @log_level = Rails.logger.level
#     @log_buffer_size = Rails.logger.auto_flushing
#   end
#   Rails.logger.flush
#   Rails.logger.instance_variable_set("@log", STDOUT)
#   Rails.logger.level = Logger::DEBUG
#   Rails.logger.auto_flushing = true
#   nil
# end
# 
# def hide_log
#   if @log_buffer_size
#     Rails.logger.instance_variable_set("@log", @log_file)
#     Rails.logger.level = @log_level
#     Rails.logger.auto_flushing = @log_buffer_size
#   end
#   nil
# end
#!/usr/bin/ruby

# begin
#   require 'hirb' # sudo gem install cldwalker-hirb --source http://gems.github.com
#   Hirb.enable
# rescue LoadError => err
#   warn "Couldn't load hirb in railsrc: #{err}"
# end

def change_log(stream)
  if defined?(Rails)
    Rails.logger = Logger.new(stream)
    # ActiveRecord::Base.logger = Rails.logger
  else
    ActiveRecord::Base.logger = Logger.new(stream)
  end
  # ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end                                   