#!/bin/zsh
# Plugin to dynamically create directory-based completions
# Author: Caio Romão <caioromao@gmail.com>
# Url: http://blog.caioromao.com

# Usage:
#  $ ls ~/Desktop/
#  >>> directory1/ directory2/ directory3/ other-dir/ fileA.txt
#
#  $ make_dir_complete newalias ~/Desktop/
#  $ newalias <TAB><TAB>
#  >>> directory1/ directory2/ directory3/ other-dir/
#  $ newalias d<TAB><TAB>
#  >>> directory1/ directory2/ directory3/

make_dir_complete() {
    if [ ${#} -ne 2 ]; then
        echo "usage: make_dir_complete <new-alias-name> <path>" 1>&2
        return 1
    fi

    local aliasname=$1

    if type $aliasname >/dev/null 2>&1; then
        echo "Error: can't overwrite previously defined command \"$1\"" 1>&2
        return 1
    fi
    if [ ! -d $2 ]; then
        echo "Error: \"$2\" doesn't point to a directory" 1>&2
    fi

    cd "$2" >/dev/null 2>&1
    local dirname=$(pwd -P)
    cd - >/dev/null 2>&1

    FUNC="$aliasname () { cd $dirname/\$@ }"
    eval $FUNC
    compctl -/ -W $dirname $aliasname
}